# Generated by Django 5.1.7 on 2025-07-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('quantite_disponible', models.IntegerField()),
                ('temps_preparation', models.IntegerField(help_text='Durée en minutes')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
