# Generated by Django 5.1.7 on 2025-07-25 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categorie_alter_plat_temps_preparation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plats/'),
        ),
        migrations.AlterField(
            model_name='plat',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='core.categorie'),
        ),
    ]
