# Generated by Django 5.1.7 on 2025-07-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plat_image_alter_plat_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('nom_client', models.CharField(max_length=100)),
                ('adresse_livraison', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plat')),
            ],
        ),
    ]
