# Generated by Django 5.1.7 on 2025-07-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisinier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('unite', models.CharField(default='unités', max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
