# Generated by Django 5.1.7 on 2025-07-27 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_commande_plat_remove_commande_quantite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='nom_produit',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='produit_id',
        ),
        migrations.RemoveField(
            model_name='lignecommande',
            name='type_produit',
        ),
        migrations.AddField(
            model_name='commande',
            name='cuisinier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_preparees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='nom_article',
            field=models.CharField(default='Article inconnu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='type_article',
            field=models.CharField(choices=[('plat', 'Plat'), ('marche', 'Marché')], default='Article inconnu', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse_livraison',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nom_client',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
