# Generated by Django 5.1.7 on 2025-07-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_commande_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
